### ISSUE TITLE
Catalog screen

### ISSUE THREAD

**Issue by odifek** [global-accelerex/rex-mpos-sdk-android-quickstart#2]
### Description
This screen shows an image list of items category. 

### Tasks

- [x] Cards of clothes, shoes, watches or belts
     - [x]  Create a `LinearLayout `containing an `ImageView ` and  `TextViews` of the Item's label and price nested within a `MaterialCardView`
     - [x]  Create a `FrameLayout` containing a `RecyclerView`
     - [x]  Create an `CatalogItem` data class having a `stringResourceId `and an `imageResourceId `both of type `Int `as parameters
     - [x] Create a `CatalogDataSource `class having a` loadItems()` function of type` List<CatalogItem>` that mimics retrieval of data from a database or a network server
     - [x]  Create an `CatalogItemAdapter` that takes data from the `CatalogDataSource` class and prepares it for the `CataLogRecyclerView` to display
- [x] Navigation to the catalog screen from the login screen
   - [x] Modify the nav_graph for conditional navigation
   - [x] Create a StateHandle to store a `KEY_LOGIN` value which state determines the navigation direction
- [x] Space between cards
